version: '3'
services:
  servicenode.api:
    build: 
      context: .
      dockerfile: ./Servicenode.Api/Dockerfile
    ports:
     - "8080:8080"
    networks:
        static-network:
            ipv4_address: 10.5.0.5
    
  snode:
    image: blocknetdx/servicenode:latest
    volumes: 
        - /c/Users/LucienPersonal/crypto/block/config:/opt/blockchain/config
        - /c/Users/LucienPersonal/crypto/block/data:/opt/blockchain/data
    command: blocknetd -rpcuser=blocknetrpcuser -rpcpassword=blocknetrpcpassword
    networks:
        static-network:
            ipv4_address: 10.5.0.6

networks:
    static-network:
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/16
                