// Copyright (c) 2014 - 2016 George Kimionis
// See the accompanying file LICENSE for the Software License Aggrement

namespace BlocknetLib.RPC.Specifications
{
    //  Note: Do not alter the capitalization of the enum members as they are being cast as-is to the RPC server
    public enum RpcMethods
    {
        //== Blockchain ==
        getbestblockhash,
        getblock,
        getblockchaininfo,
        getblockcount,
        getblockhash,
        getblockheader,
        getblockstats,
        getchaintips,
        getchaintxstats,
        getdifficulty,
        getmempoolancestors,
        getmempooldescendants,
        getmempoolentry,
        getmempoolinfo,
        getrawmempool,
        gettxout,
        gettxoutproof,
        gettxoutsetinfo,
        preciousblock,
        pruneblockchain,
        savemempool,
        scantxoutset,
        verifychain,
        verifytxoutproof,

        //== Control ==
        getmemoryinfo,
        getrpcinfo,
        help,
        logging,
        stop,
        uptime,

        //== Generating ==
        generate,
        generatetoaddress,

        //== Governance ==
        createproposal,
        listproposals,
        nextsuperblock,
        proposalfee,
        vote,

        //== Mining ==
        getblocktemplate,
        getmininginfo,
        getnetworkhashps,
        getstakingstatus,
        prioritisetransaction,
        submitblock,
        submitheader,

        //== Network ==
        addnode,
        clearbanned,
        disconnectnode,
        getaddednodeinfo,
        getconnectioncount,
        getnettotals,
        getnetworkinfo,
        getnodeaddress,
        getpeerinfo,
        listbanned,
        ping,
        setban,
        setnetworkactive,

        //== Rawtransactions ==
        analyzepsbt,
        combinepsbt,
        combinerawtransaction,
        converttopsbt,
        createpsbt,
        createrawtransaction,
        decodepsbt,
        decoderawtransaction,
        decodescript,
        finalizepsbt,
        fundrawtransaction,
        getrawtransaction,
        joinpsbts,
        sendrawtransaction,
        signrawtransactionwithkey,
        testmempoolaccept,
        utxoupdatepsbt,

        //== Servicenode ==
        servicenode,
        servicenodecount,
        servicenodecreateinputs,
        servicenodeexport,
        servicenodegenkey,
        servicenodeimport,
        servicenodelist,
        servicenoderegister,
        servicenoderemove,
        servicenodesendping,
        servicenodesetup,
        servicenodesetuplist,
        servicenodestatus,

        //== Util ==
        createmultisig,
        deriveaddresses,
        estimatesmartfee,
        getdescriptorinfo,
        signmessagewithprivkey,
        validateaddress,
        verifymessage,

        //== Wallet ==
        abandontransaction,
        abortrescan,
        addmultisigaddress,
        backupwallet,
        bumpfee,
        createwallet,
        dumpprivkey,
        dumpwallet,
        encryptwallet,
        getaddressesbylabel,
        getaddressinfo,
        getbalance,
        getnewaddress,
        getrawchangeaddress,
        getreceivedbyaddress,
        getreceivedbylabel,
        gettransaction,
        getunconfirmedbalance,
        getwalletinfo,
        importaddress,
        importprivkey,
        importprunedfunds,
        importpubkey,
        importwallet,
        keypoolrefill,
        listaddressgroupings,
        listlabels,
        listlockunspent,
        listreceivedbyaddress,
        listreceivedbylabel,
        listsinceblock,
        listtransactions,        
        listunspent,
        listwalletdir,
        listwallets,
        loadwallet,
        lockunspent,
        removeprunedfunds,
        rescanblockchain,
        sendmany,
        sendtoaddress,
        sethdseed,
        setlabel,
        settxfee,
        signmessage,
        signrawtransactionwithwallet,
        unloadwallet,
        walletlock,
        walletpassphrase,
        walletpassphrasechange,
        walletprocesspsbt,

        //2019-05-09: Added Blocknet xbridge commands
        //== XBridge ==
        dxCancelOrder,
        dxFlushCancelledOrders,
        dxGetLocalTokens,
        dxGetLockedUtxos,
        dxGetMyOrders,
        dxGetNetworkTokens,
        //2020-04-11: Added dxGetNewTokenAddress
        dxGetNewTokenAddress,
        dxGetOrder,
        dxGetOrderBook,
        dxGetOrderFills,
        dxGetOrderHistory,
        dxGetOrders,
        dxGetTokenBalances,
        //2020-04-11: Added dxGetTradingData
        dxGetTradingData,
        dxLoadXBridgeConf,
        dxMakeOrder,
        dxTakeOrder,

        //2019-05-09: Added Blocknet xrouter commands
        //== XRouter ==
        xrConnect,
        xrConnectedNodes,
        xrDecodeRawTransaction,
        xrGetBlock,
        xrGetBlockCount,
        xrGetBlockHash,
        xrGetBlocks,
        xrGetNetworkServices,
        xrGetReply,
        xrGetStatus,
        xrGetTransaction,
        xrGetTransactions,
        xrReloadConfigs,
        xrSendTransaction,
        xrService,
        xrServiceConsensus,
        xrShowConfigs,
        xrStatus,
        xrUpdateNetworkServices,

        //== Zmq ==
        getzmqnotifications,
    }
}