apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      run: blockdx-api
    name: blockdx-api
    namespace: luciendev
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: blockdx-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: blockdx-api
      spec:
        containers:
        - image: lucienmartijn/blockdx.api:v1.1.7
          imagePullPolicy: Always
          name: blockdx-api
          ports:
          - containerPort: 8086
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: blockdx-api
    namespace: luciendev
  spec:
    ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
    selector:
      run: blockdx-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List